### ISSUE TITLE
UPDATE 파일이 삭제가 안됩니다

### ISSUE THREAD

**Issue by qogusdn1017** [monun/auto-reloader#2]
[최근 업데이트 하신 build.gradle.kts](https://github.com/monun/paper-sample/blob/653ffb6db04ceef22223d82c6c2fe13fe5535971/build.gradle.kts#L40)를 제 build.gradle.kts쪽에 그대로 넣었고, 빌드 스크립트는 명령대로 잘 따라줍니다

헌데 윈도우만 이런건지 모르겠으나 AutoReloader측에서 가끔 UPDATE 파일이 삭제가 안되네요..

직접 지워보려고 하면 IntelliJ IDEA가 사용중이라고 이야기를 하는데 대체 무슨 연관인지를 모르겠습니다.

참고로 저만이 아니라 다른 사람도 동일한 증상을 겪었습니다.

삭제가 되질 않아서 리로딩 명륜진사가 되어버리네요

**Comment by monun** [comment]
프로젝트 링크 주시겠어요

**Comment by qogusdn1017** [comment]
레포 비공개라서 혹시 스크린샷으로는 어려울까요

**Comment by qogusdn1017** [comment]
![build.gradle.kts](https://user-images.githubusercontent.com/36562850/180757169-81737a55-861c-4cb6-ae0b-13332efb09c1.png)

baseName은 저는 플젝이름 그대로라 플젝이름으로했고 사진에 나와있지는 않지만 동일 조건문에 into(plugins)를 into(pluginDirectory)로 변경, 서버 디렉터리는 .debug-server -> .server로 변경했습니다.

이외에는 AutoReloader 0.0.4 넣은거 빼고는 바꾼거 없어요. 다른 OS는 어떻게 되는지 모르겠네요... 추후 리눅스쪽 테스트 해보겠습니다.

**Comment by qogusdn1017** [comment]
어... 0.0.5버전은 RELOAD라는 파일을 수동으로 삭제하는 방식인가요...?

**Comment by qogusdn1017** [comment]
우선은 수동 파일 삭제로 작동은 되니 이슈는 닫겠습니다.
